/**
 * BuildCalc Pro Resolves a ToolMetadata.iconName string to a Lucide icon.
 * Unknown names fall back to Calculator so Phase 3/4 tools can't break the UI.
 */
import {
  ArrowLeftRight,
  BrickWall,
  Calculator,
  Cylinder,
  Fence,
  FilePlus2,
  FileSpreadsheet,
  Gauge,
  Grid3x3,
  Hammer,
  House,
  Layers,
  LayoutGrid,
  Lightbulb,
  Logs,
  Mountain,
  Paintbrush,
  Percent,
  Pipette,
  Ruler,
  Scale,
  Shovel,
  Sigma,
  Square,
  Thermometer,
  TrendingUp,
  Triangle,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  ArrowLeftRight,
  BrickWall,
  Calculator,
  Cylinder,
  Fence,
  FilePlus2,
  FileSpreadsheet,
  Gauge,
  Grid3x3,
  Hammer,
  House,
  Layers,
  LayoutGrid,
  Lightbulb,
  Logs,
  Mountain,
  Paintbrush,
  Percent,
  Pipette,
  Ruler,
  Scale,
  Shovel,
  Sigma,
  Square,
  Thermometer,
  TrendingUp,
  Triangle,
  Zap,
};

export function toolIcon(iconName: string): LucideIcon {
  return ICON_MAP[iconName] ?? Calculator;
}
